Merge to Master PR
wathigo/Tic-tac-toe pull request #5
Opened 2019-06-12 19:35 UTC by wathigo

2019-06-12 21:53 UTC, AdnanAfsari commented on lib/script.rb
> +  def display
should not mix user interaction with game logic (e.g. no “puts” and “get.chomp” in lib directory!).move it to the bin.

2019-06-12 21:57 UTC, AdnanAfsari requested changes
**Hello @wathigo @othman-19 Nice work,almost there **

Everything looks good but you have to make a small change, please check my comment for that and make change according to that and submit for another review.

Happy Coding :)

2019-06-13 09:35 UTC, wathigo commented
Thank you @AdnanAfsari .  We have implemented the necessary changes

2019-06-13 16:48 UTC, AdnanAfsari commented
Hello @wathigo @othman-19 , Congratulation 👍 

Looks good, you can go ahead and merge the branch

Happy Coding

2019-06-13 16:57 UTC, merged